name: dedi-web code CI
on:
  workflow_call:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        node-version: [16.x, 18.x, 20.x]

    name: test/${{ matrix.node-version }}/${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install
        run: npm install

      - name: lint
        run: npm run lint

      - name: Unit Tests
        run: npm run test

      - name: build
        run: npm run build