name: dedi-web code CI
on:
  workflow_call:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        node-version: [22.x, 23.x, 24.x]

    name: test/${{ matrix.node-version }}/${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        run: npm ci

      - name: lint
        run: |
          npm run lint

      - name: Tests
        run: npm run test

      - name: build
        run: npm run build
