name: github-pages-deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Node
        uses: actions/setup-node@v4
        with:
          node-version: "21.0.0"

      - name: Install, test, and build
        run: |
          npm ci
          npm run lint
          npm run test
          npm run build

      - name: Deploy to GH Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist
          branch: gh-pages
